name: SNS Trend Screenshot

on:
  workflow_dispatch:

  schedule:
    # 한국시간 월요일 09:10
    - cron: '10 0 * * 1'

    # 한국시간 목요일 09:10
    - cron: '10 0 * * 4'

permissions:
  contents: write

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download full screenshot
        env:
          ACCESS_KEY: ${{ secrets.SCREENSHOTONE_ACCESS_KEY }}
        run: |
          curl --location \
            --get "https://api.screenshotone.com/take" \
            --data-urlencode "access_key=${ACCESS_KEY}" \
            --data-urlencode "url=https://claude.ai/artifact/661fBc9hrzkFAv3JvS8E7V" \
            --data-urlencode "format=jpg" \
            --data-urlencode "block_ads=true" \
            --data-urlencode "block_cookie_banners=true" \
            --data-urlencode "block_banners_by_heuristics=false" \
            --data-urlencode "
